In [3]:
a = 8
a

8

In [2]:
a

8

In [4]:
b =  4
b

4

In [5]:
"heeloo"

'heeloo'

In [6]:
 "wifoljoil'"

"wifoljoil'"

In [7]:
'wheudhiwe"'

'wheudhiwe"'

In [8]:
3+8

11

In [9]:
98/10

9.8

In [10]:
98%10

8

In [11]:
import numpy as np

In [18]:
a = np.array([1,2,3])
b = np.array([3,4,5])
a*b

array([ 3,  8, 15])

In [19]:
b

array([3, 4, 5])

In [20]:
c = np.array([[2,2],[3,3]])
c

array([[2, 2],
       [3, 3]])

In [21]:
d = np.array([[2,3],[4,5]])
d

array([[2, 3],
       [4, 5]])

In [22]:
c * d

array([[ 4,  6],
       [12, 15]])

In [23]:
c.dot(d)

array([[12, 16],
       [18, 24]])

In [18]:
lst = input()
#lst=lst.strip("0")
#if lst=="":
#    lst = "0"

print(int(lst[::-1]))

5566000
6655


In [20]:
int("0005446534")

5446534

# 學校矩陣加法

In [17]:
list1=[[1,2,3,4,5],[6,7,8,9,10],[11,12,13,14,15]]
list2=[[1,2,3,4,5],[6,7,8,9,10],[11,12,13,14,15]]
ans=[[0,0,0,0,0],[0,0,0,0,0],[0,0,0,0,0]]

def show_arr(arr):
    for i in range(len(arr)):
        for j in range(len(arr[0])):
             print(arr[i][j],",", end="")
        print()

for i in range(len(list1)):
    for j in range(len(list2[0])):
        ans[i][j]=list1[i][j]+list2[i][j]
show_arr(ans)

2 ,4 ,6 ,8 ,10 ,
12 ,14 ,16 ,18 ,20 ,
22 ,24 ,26 ,28 ,30 ,


In [19]:
list1=[[1,2,3,4,5],[6,7,8,9,10],[11,12,13,14,15]]
list2=[[1,2,3,4,5],[6,7,8,9,10],[11,12,13,14,15]]
ans=[]

def show_arr(arr):
    for i in range(len(arr)):
        for j in range(len(arr[0])):
             print(arr[i][j],",", end="")
        print()

for i in range(len(list1)):
    ans.append([])
    for j in range(len(list2[0])):
        ans[i].append(list1[i][j]+list2[i][j])
show_arr(ans)

2 ,4 ,6 ,8 ,10 ,
12 ,14 ,16 ,18 ,20 ,
22 ,24 ,26 ,28 ,30 ,


# 矩陣乘法

In [22]:
list1=[[1,3],[2,4],[5,6]]
list2=[[1,2,3],[4,5,6]]
ans=[[0,0,0],[0,0,0],[0,0,0]]

def show_arr(arr):
    for i in range(len(arr)):
        for j in range(len(arr[0])):
             print(arr[i][j],",", end="")
        print()
        
for i in range(len(list1)):
    for j in range(len(list2[0])):
        
        for k in range(len(list1[0])):
            ans[i][j]+=list1[i][k]*list2[k][j]
show_arr(ans)           


13 ,17 ,21 ,
18 ,24 ,30 ,
29 ,40 ,51 ,


In [25]:
list1=[[1,3],[2,4],[5,6]]
list2=[[1,2,3],[4,5,6]]
ans=[[0]*len(list2[0]) for i in range(len(list1))]

def show_arr(arr):
    for i in range(len(arr)):
        for j in range(len(arr[0])):
             print(arr[i][j],",", end="")
        print()
        
for i in range(len(list1)):
    for j in range(len(list2[0])):
        
        for k in range(len(list1[0])):
            ans[i][j]+=list1[i][k]*list2[k][j]
show_arr(ans)  

13 ,17 ,21 ,
18 ,24 ,30 ,
29 ,40 ,51 ,


In [23]:
list1=[[1,3],[2,4],[5,6]]
list2=[[1,2,3],[4,5,6]]
ans=[]

def show_arr(arr):
    for i in range(len(arr)):
        for j in range(len(arr[0])):
             print(arr[i][j],",", end="")
        print()
        
for i in range(len(list1)):
    ans.append([])
    for j in range(len(list2[0])):
        ans[i].append(0)
        for k in range(len(list1[0])):
            ans[i][j]+=list1[i][k]*list2[k][j]
show_arr(ans)    

13 ,17 ,21 ,
18 ,24 ,30 ,
29 ,40 ,51 ,


In [24]:
list1=[[1,3],[2,4],[5,6]]
list2=[[1,2,3],[4,5,6]]
ans=[]

def show_arr(arr):
    for i in range(len(arr)):
        for j in range(len(arr[0])):
             print(arr[i][j],",", end="")
        print()
        
for i in range(len(list1)):
    ans.append([])
    for j in range(len(list2[0])):
        s=0
        for k in range(len(list1[0])):
            s+=list1[i][k]*list2[k][j]
        ans[i].append(s)
show_arr(ans)    

13 ,17 ,21 ,
18 ,24 ,30 ,
29 ,40 ,51 ,


In [7]:
len(list1[0])

5

In [5]:
print(len(list1))
print(len(list2))

3
3


In [2]:
[[0]*5 for i in range(3)] # for comprehension

[[0, 0, 0, 0, 0], [0, 0, 0, 0, 0], [0, 0, 0, 0, 0]]

In [3]:
[0]*5

[0, 0, 0, 0, 0]

In [4]:
lst = []
for i in range(3):
    lst.append([0]*5)
lst

[[0, 0, 0, 0, 0], [0, 0, 0, 0, 0], [0, 0, 0, 0, 0]]